all:
	psql -d swe3613 -U swe3613 -f create_databases.SQL
	psql -d swe3613 -U swe3613 -f ICD_9_DESCRIPTIONS.SQL
	psql -d swe3613 -U swe3613 -f ICD_10_DESCRIPTIONS.SQL
	psql -d swe3613 -U swe3613 -f GEMS_DATA.SQL

